---
title: "Lab 07 - University of Edinburgh Art Collection"
author: "Insert your name here"
date: "Insert date here"
output: github_document
editor_options: 
  chunk_output_type: console
---

### Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse) 
library(skimr)
library(rvest)
library(robotstxt)
```

```{r}
paths_allowed("https://collections.ed.ac.uk/art)")
```

```{r load-data, message = FALSE, eval = FALSE}
# Remove eval = FALSE or set it to TRUE once data is ready to be loaded
uoe_art <- read_csv("data/uoe-art.csv")
```

### Exercise 9

```{r separate-title-date, error = TRUE}
uoe_art <- uoe_art %>%
  separate(title, into = c("title", "date"), sep = "\\(") %>%
  mutate(year = str_remove(date, "\\)") %>% as.numeric()) %>%
  select(title, artist, year, link)
```

### Exercise 10

Remove this text, and add your answer for Exercise 1 here.
Add code chunks as needed.
Don't forget to label your code chunk.
Do not use spaces in code chunk labels.


115 have artist info missing. 1402 have year info missing. 

### Exercise 11

ggplot(uoe_art, aes(x = year)) +
geom_hist
```{r}
uoe_art %>%
  ggplot(uoe_art, aes(x = year)) +
geom_histogram()
```

### Exercise 13
Add exercise headings as needed.
```{r}
uoe_art %>%
  count(artist) %>%
  arrange(desc(n))
```

```{r}
  dplyr::filter(uoe_art, grepl('Child|child', title))
```

